# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Verify JAVA SDK

on:
  push:
    branches: [ master ]
    paths: 
      - 'sdk/java/**'
      - '!sdk/java/README.md'
  pull_request:
    branches: [ master ]
    paths: 
      - 'sdk/java/**'
      - '!sdk/java/README.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/sdk/java/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Verify with Maven
      run: |
        mvn -B -f sdk/java/pom.xml clean install verify
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish package
        run: mvn -B -f sdk/java/pom.xml deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
